name : maven with java ci
on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup jdk 11
    - uses:  actions/java@v3
      with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
    - name: Build with Maven
      run: mvn -b package --file pom.xml     
       

 
